### ISSUE TITLE
🔦[Spike] Copy xpubkey process

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/Litewallet-Project#20]
## Query
How difficult is is to make it possible for users to use`xpubkey` in Litewallet

## Screenshot
<img width="714" alt="Screen Shot 2021-03-15 at 10 34 50 AM" src="https://user-images.githubusercontent.com/2899463/111140303-192fcf00-857a-11eb-93b2-76f211a6b363.png">

**Comment by losh11** [comment]
I believe this will output the xpub key.
https://github.com/breadwallet/breadwallet-core/blob/73566cb79f753954eccbf07d5ab25ca54741198e/support/BRBIP32Sequence.h#L106
Then you will just have to format it as a QR code and a string.

**Comment by kcw-grunt** [comment]
Did some research and produced a mockup.  
@losh11 @wangxinxi will you let me know that this use case is valid?  Is anything missing?

|Markup of Xpub key Use Case|
|------------------------------|
|![Untitled87](https://user-images.githubusercontent.com/2899463/133925894-68b1a681-93e1-4fe9-9aae-7dbba646ecc4.png)|

cc:
@litecoin-foundation/litewallet-team

**Comment by losh11** [comment]
I think this is mostly good. One addition prior to showing the xpub key is
asking which prefix they’d like. Historically we’ve used the xpub prefix in
Litecoin Core, but a lot of other Litecoin software want the newer Lpub
format.

**Comment by kcw-grunt** [comment]
Ok. Thanks @losh11.
Can you guys provide the link  of the process to add the xpub key to LTCPay server?  Assuming there is documentation.

**Comment by kcw-grunt** [comment]
Also regarding the xpub format.  Would this sample make sense?:

|Client Type| xpub address example|
|------------|-------|
|BitcoinCore|`xpub67uA5wAUuv1ypp7rEY7jUZBZmwFSXXcFUArLBJrHr3amnymkUEYWzQJz13zLacZv33sSuxKVmerpZeFExapBNt8HpAqtTtWqDQRAgyqSKUHu`|
|LitcoinCore|`lpub67uA5wAUuv1ypp7rEY7jUZBZmwFSXXcFUArLBJrHr3amnymkUEYWzQJz13zLacZv33sSuxKVmerpZeFExapBNt8HpAqtTtWqDQRAgyqSKUHu`|
|Litewallet|`lwpub67uA5wAUuv1ypp7rEY7jUZBZmwFSXXXFUArLBJrHr3amnymkUEYWzQJz13zLacZv33sSuxKVmerpZeFExapBNt8HpAqtTtWqDQRAgrrSKUX`|

@losh11  ☝🏾

**Comment by losh11** [comment]
Just Lpub or xpub. These prefixes don’t belong to any specific wallet, it’s
just that some software only allows using either Lpub or xpub, not both.
Only software that I’ve seen which supports both is Ian Coleman’s BIP39
tools.

**Comment by kcw-grunt** [comment]
Ok.Got it.
